// Photos: put a file with the name shown in "i" inside the images folder
// (for example images/places/ellora-caves.jpg). jpg, jpeg, png or webp all work.
// ===== EDIT THIS FILE to change phone, places and hotels =====
// EDIT HERE: your phone number with country code, no + or spaces (India = 91)
var PHONE = "919518526061";
// EDIT HERE: your email address
var EMAIL = "dokhaleganesh381@gmail.com";

var PLACES = [
 {i:"images/places/ellora-caves",n:"Ellora Caves",c:"Caves",d:"30 km",t:"Closed Tuesday",x:"UNESCO World Heritage site with 34 rock-cut Buddhist, Hindu and Jain caves. Cave 16, the Kailasa Temple, is carved from a single rock.",e:"₹40 Indians, ₹600 foreigners (video camera extra)",ti:"9:00 AM to 5:30 PM, closed Tuesday",w:"Give at least 3 hours. Start with Cave 16 (Kailasa Temple) early to avoid crowds and heat."},
 {i:"images/places/ajanta-caves",n:"Ajanta Caves",c:"Caves",d:"105 km",t:"Closed Monday",x:"Buddhist caves famous for ancient wall paintings. Plan a full day; it is best from October to March.",e:"₹40 Indians, ₹600 foreigners",ti:"9:00 AM to 5:00 PM, closed Monday",w:"Buses run from the ticket counter to the caves; private vehicles cannot go all the way. Carry water."},
 {i:"images/places/bibi-ka-maqbara",n:"Bibi Ka Maqbara",c:"Heritage",d:"5 km",t:"Open daily",x:"A white tomb built in the 1660s, often called the Taj of the Deccan. Lovely at sunset.",e:"₹25 Indians, ₹300 foreigners",ti:"6:00 AM to 8:00 PM, open all days",w:"Best photos are early morning or just before sunset, from the reflecting pool at the entrance."},
 {i:"images/places/daulatabad-fort",n:"Daulatabad Fort",c:"Heritage",d:"15 km",t:"Open daily",x:"Hilltop fort once known as Devgiri, with a dark spiral passage, moats and a long climb with big views.",e:"₹25 Indians, ₹300 foreigners",ti:"6:00 AM to 6:00 PM, open all days",w:"The climb takes 1.5 to 2 hours. Wear good shoes and carry a torch for the dark passage inside."},
 {i:"images/places/panchakki",n:"Panchakki",c:"Heritage",d:"3 km",t:"Open daily",x:"A 17th-century water mill and dargah, with a calm tank and garden where you can rest.",e:"₹15 approx",ti:"7:00 AM to 9:00 PM, open all days",w:"A short, easy visit. Good to combine with Aurangabad Caves or Bibi Ka Maqbara on the same trip."},
 {i:"images/places/aurangabad-caves",n:"Aurangabad Caves",c:"Caves",d:"4 km",t:"Open daily",x:"Nine Buddhist caves on a hillside, and a good short visit before you see Ellora.",e:"Free entry (small camera fee may apply)",ti:"8:00 AM to 6:00 PM, open all days",w:"Fewer crowds than Ellora. Good for sunrise or sunset views over the city."},
 {i:"images/places/grishneshwar-temple",n:"Grishneshwar Temple",c:"Temples",d:"30 km",t:"Open daily",x:"One of the twelve Jyotirlingas, next to Ellora. Visit early in the morning to avoid queues.",e:"Free entry",ti:"5:30 AM to 9:30 PM, open all days",w:"Go early morning to avoid long queues, especially on Monday."},
 {i:"images/places/khuldabad-bhadra-maruti",n:"Khuldabad and Bhadra Maruti",c:"Temples",d:"25 km",t:"Open daily",x:"A quiet town with Aurangzeb's simple tomb and the Bhadra Maruti temple, where Hanuman is shown reclining.",e:"Free entry",ti:"Open all day",w:"A quiet, less-visited stop. Combine it with Ellora and Grishneshwar since they are close together."},
 {i:"images/places/soneri-mahal",n:"Soneri Mahal",c:"Heritage",d:"12 km",t:"Open daily",x:"A small Mughal-era palace on a hill, now a museum, with fine views over the city.",e:"₹25 approx",ti:"10:00 AM to 5:00 PM, closed Friday",w:"Small museum, quick visit. Good hilltop view over the city."},
 {i:"images/places/siddharth-garden-zoo",n:"Siddharth Garden and Zoo",c:"Gardens",d:"2 km",t:"Closed Monday",x:"A city garden and zoological park, easy with children and elders.",e:"₹10 to ₹20 approx",ti:"8:00 AM to 6:00 PM, closed Monday",w:"Easy for families with children or elders; benches and shade throughout."},
 {i:"images/places/himayat-bagh",n:"Himayat Bagh",c:"Gardens",d:"4 km",t:"Open daily",x:"A large green space with old trees and walking paths, good for a slow morning.",e:"Free entry",ti:"Open daylight hours",w:"Good for an early morning walk before the caves get busy."},
 {i:"images/places/salim-ali-lake",n:"Salim Ali Lake",c:"Gardens",d:"2 km",t:"Open daily",x:"A lake near Delhi Gate with a bird-watching area and a garden on the shore.",e:"Free entry",ti:"Open daylight hours",w:"Visit at sunset when local birds return to the lake."},
 {i:"images/places/jayakwadi-dam-paithan",n:"Jayakwadi Dam and Paithan",c:"Gardens",d:"50 km",t:"Open daily",x:"A large dam with a bird sanctuary and a garden, and the town of Paithan, known for handwoven Paithani sarees.",e:"Small entry fee at the garden",ti:"Best visited daytime",w:"Combine with a stop in Paithan town to see or buy Paithani sarees."}
];
var HOTELS = [
 {i:"images/hotels/hotel-jagdamba",n:"Jagdamba Hotel",c:"Budget stay",p:"From about ₹500 per night",x:"Near Old Toll Nakka, Boladgaon, Chikalthana, Aurangabad.",ti:"Check-in 12:00 PM, check-out 11:00 AM",w:"Simple rooms with AC and non-AC options. Good for a night's stay near the airport road area."},
 {i:"images/hotels/hotel-railway-station",n:"Budget hotel near Railway Station",c:"Budget stay",p:"From about ₹923 per night",x:"Near Railway Station, Dr. Bhapkar Marg, Aurangabad.",ti:"Check-in 12:00 PM, check-out 11:00 AM",w:"Close to the railway station, useful if you are arriving late or leaving early by train."},
 {i:"images/hotels/hotel-ginger",n:"Ginger Hotel",c:"Mid-range stay",p:"Ask us for today's rate",x:"Modern city hotel. Ask us for address and room options.",ti:"Check-in 12:00 PM, check-out 11:00 AM",w:"A clean, no-frills business hotel chain. Ask us for the current address and price."},
 {i:"images/hotels/hotel-hyatt-place",n:"Hyatt Place",c:"Premium stay",p:"Ask us for today's rate",x:"Modern business hotel with a large glass lobby. Ask us for address and room options.",ti:"Check-in 2:00 PM, check-out 12:00 PM",w:"Modern rooms, restaurant and gym on site. Good for business travellers and families."},
 {i:"images/hotels/hotel-5star-jalna-road",n:"5-star hotel on Jalna Road",c:"5-star stay, rated 4.5 out of 5",p:"From about ₹6,775 per night",x:"R-3, Jalna Rd, Town Center, Chikalthana. Set in 13 acres of gardens with pool views, tennis courts and the Madhuban restaurant.",ti:"Check-in 2:00 PM, check-out 12:00 PM",w:"13 acres of gardens, a pool, tennis courts and the Madhuban restaurant. Good for a relaxed multi-day stay."},
 {i:"images/hotels/hotel-rama-international",n:"Rama International Hotel",c:"Mid-range stay",p:"Ask us for today's rate",x:"Ask us for the address and room options.",ti:"Check-in 12:00 PM, check-out 11:00 AM",w:"Tell us your dates and we will confirm availability and the best rate."}
];

// Nearest railway station, airport and road links. k = drawing (Travel, Air or Road)
var TRAVEL = [
 {i:"images/travel/train-station",k:"Travel",n:"Chhatrapati Sambhajinagar Railway Station",c:"By train",m:["Station code AWB","Inside the city"],x:"The main station, renamed from Aurangabad. Some tickets and signs still say Aurangabad. Most city hotels are a 10 to 20 minute taxi ride away. Direct trains run from Mumbai, Hyderabad and other big cities. Check IRCTC for timings.",w:"We can arrange a taxi to pick you up from the station and take you straight to your hotel."},
 {i:"images/travel/airport",k:"Air",n:"Chhatrapati Sambhajinagar Airport",c:"By air",m:["Airport code IXU","About 10 km from the city"],x:"The airport is at Chikalthana and has flights from major cities. Taxis wait outside. Some of our hotels in Chikalthana are close to the airport.",w:"Prepaid taxis and app cabs are available outside the terminal. Tell us your flight time and we can arrange pickup."},
 {i:"images/travel/jalgaon-station",k:"Travel",n:"Jalgaon Railway Station",c:"Nearest station for Ajanta",m:["About 60 km from Ajanta"],x:"If you plan to see Ajanta Caves first, Jalgaon is the nearest large railway station. From the city, Ajanta is about 105 km by road.",w:"From Jalgaon, taxis and buses connect to Ajanta Caves, about 60 km away."},
 {i:"images/travel/road-samruddhi",k:"Road",n:"Samruddhi Mahamarg",c:"By road",m:["Pune about 235 km","Mumbai about 335 km"],x:"State and private buses run from Pune, Mumbai, Nashik and Jalgaon. The Samruddhi Mahamarg expressway runs through this region and makes road trips easier. We can also arrange a taxi or a car with a driver for your whole trip.",w:"We can arrange a car with a driver for the full road trip, including stops on the way."}
];

// Sample blog posts. Replace them with your own.
var POSTS = [
 {t:"Ellora or Ajanta: which one should you see first?",d:"12 September 2026",g:"Caves",x:"Ellora is about 30 km from the city and is the easier day trip. You can see Buddhist, Hindu and Jain caves in one place, including the huge Kailasa Temple carved from a single rock. Ajanta is about 105 km away and is best for its ancient wall paintings. If you have one day, choose Ellora. If you have two, see both on separate days. Ellora is closed on Tuesday and Ajanta on Monday."},
 {t:"The best time to visit Chhatrapati Sambhajinagar",d:"5 September 2026",g:"Planning",x:"October to February is cool and comfortable, and it is the best time for long days at the caves and the fort. From July to September the rains turn the hills green and waterfalls appear near the caves, but paths can be slippery. From March to June it is hot, so start sightseeing early in the morning."},
 {t:"A one-day city tour plan",d:"28 August 2026",g:"Itinerary",x:"Start at Bibi Ka Maqbara in the morning, then visit Panchakki and Aurangabad Caves. After lunch, walk through Siddharth Garden and end the day by Salim Ali Lake or Himayat Bagh. You can do all of this by taxi or auto. Ask us to arrange a driver for the day."},
 {t:"What to eat and what to bring home",d:"15 August 2026",g:"Food and shopping",x:"Try Naan Qalia, the city's famous dish of spiced mutton curry with soft naan. Ask your hotel for vegetarian options too. For a gift, look for handwoven Paithani sarees, which come from Paithan, about 50 km from the city."}
];